# -*- coding: utf-8 -*-
"""Resume Analyzer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJVegfBbwrvE-o1u5GebyChbwgTRrY2q
"""

import re

def extract_personal_info(text):
    name = re.search(r'Name: (\w+\s\w+)', text,)
    place = re.search(r'Place: (\w+\s\w+)', text)
    phone = re.search(r'Phone: (\d+)', text)
    email = re.search(r'Email: (\S+)', text)
    social_media = re.findall(r'(https?://\S+)', text)
    return {
        'name': name.group(1) if name else None,
        'place': place.group(1) if place else None,
        'phone': phone.group(1) if phone else None,
        'email': email.group(1) if email else None,
        'social_media': social_media
    }

def extract_education(text):
    undergraduation = re.search(r'Undergraduation: (\w+\s\w+)', text,)
    high_school = re.search(r'High School: (\w+\s\w+)', text)
    return {
        'undergraduation': undergraduation.group(1) if undergraduation else None,
        'high_school': high_school.group(1) if high_school else None,
    }

def extract_work_experience(text):
    experience = re.search(r'Experience: (\d+)', text)
    companies = re.findall(r'(?:Company|Organization): (\w+\s\w+)', text)
    location = re.findall(r'(?:Location|Places): (\w+\s\w+)', text)
    duration = re.findall(r'(?:Duration|Period): (\d+)', text)
    designation = re.findall(r'(?:Designation|Role): (\w+\s\w+)', text)
    return {
        'experience': experience.group(1) + ' Months' if experience else None,
        'companies': companies,
        'location': location,
        'duration': duration,
        'designation': designation
    }

def extract_projects(text):
    projects = re.findall(r'(Projects|Publications): (\w+\s\w+)', text)
    return {
        'projects': projects
    }

def extract_skills(text):
    skills = re.findall(r'(Skills|Tools): (\w+\s\w+)', text)
    return {
        'skills': skills
    }

def analyze_resume(file_path):
    with open(file_path, 'r') as f:
        text = f.read()
    personal_info = extract_personal_info(text)
    education = extract_education(text)
    work_experience = extract_work_experience(text)
    projects = extract_projects(text)
    skills = extract_skills(text)
    return {
        'personal_info': personal_info,
        'education': education,
        'work_experience': work_experience,
        'projects': projects,
        'skills': skills
    }

resume_file = '/content/resume.txt'
resume_data = analyze_resume(resume_file)
print(resume_data)